# Basic setup:
title: Kyle Lemons
description: Go Programming Blog
google_analytics: UA-1350650-1

# Directory setup:
permalink: pretty
include:
  - _pages
defaults:
  - scope:
      path: assets/images
    values:
      image: true
collections:
  projects:
    output: true
    permalink: /go/:name
excerpt_separator: "<!-- snip -->"

# Display / Rendering:
timezone: America/Los_Angeles
encoding: utf-8

# Serve options:
incremental: false
livereload: true

# Jekyll options:
strict_front_matter: true

# Default author:
author: Kyle Lemons

# Plugins:
plugins:
- jekyll-redirect-from
