# Minimal theme:
#   https://github.com/pages-themes/minimal
theme: jekyll-theme-minimal

# Basic setup:
title: Kyle Lemons
description: Articles, guides, documentation, etc.
logo: assets/images/logo.jpg

# Directory setup:
permalink: pretty
include:
  - _pages
defaults:
  - scope:
      path: assets/images
    values:
      image: true

# Display / Rendering:
timezone: America/Los_Angeles
encoding: utf-8

# Serve options:
incremental: false
livereload: true

# Jekyll options:
strict_front_matter: true

# Default author:
author: Kyle Lemons
