version: '3'
services:
    jekyll:
        image: jekyll/jekyll:3.8
        volumes:
            - .:/srv/jekyll
            - ./.bundlecache:/usr/local/bundle
        command: ["jekyll", "serve", "--force-polling"]
        ports:
            - 4000:4000
            - 35729:35729
